services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ALLOW_INTERNAL_REQUESTS=false #optional
    volumes:
      - ./config:/config
    ports:
      - 81:80
      - 444:443
    labels:
      - "homepage.group=Servicios"
      - "homepage.name=Heimdall"
      - "homepage.icon=heimdall.png"
      - "homepage.href=http://192.168.1.120:81"
      - "homepage.description=Dashboard alternativo"
    restart: unless-stopped
